### ISSUE TITLE
Preparing for the Professional Data Engineer exam 

### ISSUE THREAD

**Issue by vochicong** [vochicong/vochicong.github.io#4]
https://www.coursera.org/learn/preparing-cloud-professional-data-engineer-exam

- [x] Videos
- [x] Quizzes
- [x] Labs
- [x] Final tests
- [x] #19 Welcome to Preparing for the Professional Data Engineer Exam
- [x] #20 Sample Case Studies for the Professional Data Engineer Exam
- [ ] #21 Designing and Building
- [ ] #22 Analyzing and Modeling
- [ ] #23 Reliability, Policy, and Security
- [ ] #24 Resources and next steps
